homepage: "https://firebase.google.com/docs/firestore/"
primary_contact: "varconst@google.com"
auto_ccs:
  - "varconst@google.com"
  - "minafarid@google.com"
  - "rgowman@google.com"
sanitizers:
  - address
  - undefined
