homepage: "https://github.com/google/skia"
primary_contact: "kjlubick@chromium.org"
auto_ccs:
  - "hcm@chromium.org"
  - "mtklein@chromium.org"
  - "reed@google.com"
  - "bsalomon@google.com"
  - "caryclark@google.com"
  - "liyuqian@google.com"
sanitizers:
 - address
 - undefined
 - memory
