homepage: "http://www.boost.org/"

# TODO: add more boost maintainers here and possibly a mailing list.
# primary_contact: "someone@boost.org"
auto_ccs:  
   - "jz.maddock@googlemail.com"
#   - "someone-else@boost.org"
