homepage: https://webkit.org/
fuzzing_engines:
  - none
sanitizers:
  - address
auto_ccs:
  - "fpizlo@apple.com"
  - "mark.lam@apple.com"
  - "akilsrin@apple.com"
  - "ddkilzer@apple.com"
  - "jfb@chromium.org"
  - "sbarati@apple.com"
