homepage: "https://www.unicorn-engine.org"
primary_contact: "unicorn.emu@gmail.com"
auto_ccs : "p.antoine@catenacyber.fr"

sanitizers:
- address
- memory
- undefined

# FIXME: Remove after unicorn-engine/unicorn#1007 is checked in.
disabled: true
