# Provide the home page for *your* project:
homepage: "https://my-api.example.com"
# Provide the e-mail for the primary contact:
primary_contact: "primary-my-api-maintainer@example.com"
auto_ccs:
  - "secondary-my-api-maintainer@example.com"
  - "tertiary-my-api-maintainer@example.com"
