apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  selector:
    app: jenkins-master
  ports:
  - name: agent
    port: 50000
  - name: https
    port: 443
    targetPort: 8082
