homepage: "https://www.qubes-os.org/"
primary_contact: "jpo@vt.edu"
auto_ccs:
 - "joanna@invisiblethingslab.com"
 - "marmarek@invisiblethingslab.com"
 - "paras.chetal@gmail.com"
sanitizers:
 - address
 - memory
