homepage: "http://www.graphicsmagick.org/"
primary_contact: "bobjfriesenhahn@gmail.com"
auto_ccs:
    - glennrp@gmail.com
    - alex.gaynor@gmail.com
    - paul.l.kehrer@gmail.com
sanitizers:
    - address
    - memory
    - undefined
