homepage: "https://www.mercurial-scm.org/"
primary_contact: "durin42@gmail.com"
auto_ccs:
  - "gregory.szorc@gmail.com"
  - "kbullock@ringworld.org"
  - "security@mercurial-scm.org"
  - "martinvonz@google.com"
sanitizers:
  - address
  - undefined
  # TODO: re-enable memory when we figure out how to work with cpython
  # and msan at the same time.
  # - memory
