homepage: "http://llvm.org/"
primary_contact: "kcc@google.com"
auto_ccs:
  - "mascasa@google.com"
  - "jdevlieghere@apple.com"
  - "vsk@apple.com"
  - "llvm-bugs@lists.llvm.org"

# TODO(kcc): enable msan.
sanitizers:
  - address
  - undefined

# The LLVM build currently supports only libFuzzer
fuzzing_engines:
    - libfuzzer

# Bug reports are public by default:
view_restrictions: none
