homepage: "https://www.chromium.org"
primary_contact: "dgreid@chromium.org"
auto_ccs:
  - "hychao@chromium.org"
  - "cychiang@chromium.org"
  - "wuchengli@chromium.org"
  - "chinyue@chromium.org"
  - "itspeter@chromium.org"
