homepage: "https://open62541.org/"
primary_contact: "git@s.profanter.me"
auto_ccs:
 - "julius.pfrommer@iosb.fraunhofer.de"
 - "f.palm@plt.rwth-aachen.de"
 - "chris_paul.iatrou@tu-dresden.de"
sanitizers:
- address
- undefined
- memory