homepage: "https://github.com/h2o/h2o"
primary_contact: "jonathan.foote@gmail.com"
auto_ccs:
  - "frederik.deweerdt@gmail.com"
  - "kazuhooku@gmail.com"
  - "security@fastly.com"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
