homepage: "https://github.com/libarchive/libarchive"
primary_contact: "joerg.sonnenberger@googlemail.com"
auto_ccs:
  - "kientzle@gmail.com"
  - "martin@matuska.org"
fuzzing_engines:
  - libfuzzer
  - afl
