homepage: "https://www.mozilla.org/firefox/"
primary_contact: "agaynor@mozilla.com"
auto_ccs:
  - choller@mozilla.com
  - pdknsk@gmail.com
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
run_tests: False
