homepage: "http://www.grpc.io/"
primary_contact: "mattkwong@google.com"
auto_css:
  - "grpc-c-team@google.com"
  - "ctiller@google.com"
  - "dgq@google.com"
  - "klempner@google.com"
  - "jkolhe@google.com"
  - "roth@google.com"
  - "ncteisen@google.com"
  - "nnoble@google.com"
  - "sreek@google.com"
  - "vpai@google.com"
  - "yangg@google.com"
  - "yuxuanli@google.com"
  - "zyc@google.com"
