homepage: "http://www.grpc.io/"
primary_contact: "mattkwong@google.com"
auto_ccs:
  - "dgq@google.com"
  - "juanlishen@google.com"
  - "roth@google.com"
  - "ncteisen@google.com"
  - "nnoble@google.com"
  - "sreek@google.com"
  - "vpai@google.com"
  - "yangg@google.com"
  - "yashkt@google.com"
  - "yuxuanli@google.com"
  - "zyc@google.com"
coverage_extra_args: -ignore-filename-regex=.*\.cache.*
